"""adding relationships in table

Revision ID: 802d91b40b19
Revises: 4ad86a54f806
Create Date: 2025-06-12 15:26:57.366791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802d91b40b19'
down_revision: Union[str, None] = '4ad86a54f806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    # ### end Alembic commands ###
