"""joining Product and Users table

Revision ID: f775c2b463a5
Revises: 698cd0d8a9f2
Create Date: 2025-06-10 17:32:48.003581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f775c2b463a5'
down_revision: Union[str, None] = '698cd0d8a9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'created_by')
    # ### end Alembic commands ###
